#include "Debug.h"
#include "FileMan.h"
#include "LoadSaveBullet.h"
#include "LoadSaveData.h"
#include "Overhead.h"


void ExtractBulletFromFile(HWFILE const file, BULLET* const b)
{
	FileDataReader{128, file}
	  >> skip<4>
	  >> b->pFirer
	  >> b->target
	  >> b->bStartCubesAboveLevelZ
	  >> b->bEndCubesAboveLevelZ
	  >> b->sGridNo
	  >> skip<2>
	  >> b->usLastStructureHit
	  >> b->qCurrX
	  >> b->qCurrY
	  >> b->qCurrZ
	  >> b->qIncrX
	  >> b->qIncrY
	  >> b->qIncrZ
	  >> b->ddHorizAngle
	  >> b->iCurrTileX
	  >> b->iCurrTileY
	  >> b->bLOSIndexX
	  >> b->bLOSIndexY
	  >> b->fCheckForRoof
	  >> skip<1>
	  >> b->iCurrCubesZ
	  >> b->iLoop
	  >> b->fAllocated
	  >> b->fToDelete
	  >> b->fLocated
	  >> b->fReal
	  >> b->fAimed
	  >> skip<3>
	  >> b->uiLastUpdate
	  >> b->ubTilesPerUpdate
	  >> skip<1>
	  >> b->usClockTicksPerUpdate
	  >> skip<4>
	  >> b->sTargetGridNo
	  >> b->sHitBy
	  >> skip<2>
	  >> b->iImpact
	  >> b->iImpactReduction
	  >> b->iRange
	  >> b->iDistanceLimit
	  >> b->usFlags
	  >> skip<2>
	  >> b->pAniTile
	  >> b->pShadowAniTile
	  >> b->ubItemStatus
	  >> skip<3>;
}


void InjectBulletIntoFile(HWFILE const file, BULLET const* b)
{
	FileDataWriter{128, file}
	  << skip<4>
	  << b->pFirer
	  << b->target
	  << b->bStartCubesAboveLevelZ
	  << b->bEndCubesAboveLevelZ
	  << b->sGridNo
	  << skip<2>
	  << b->usLastStructureHit
	  << b->qCurrX
	  << b->qCurrY
	  << b->qCurrZ
	  << b->qIncrX
	  << b->qIncrY
	  << b->qIncrZ
	  << b->ddHorizAngle
	  << b->iCurrTileX
	  << b->iCurrTileY
	  << b->bLOSIndexX
	  << b->bLOSIndexY
	  << b->fCheckForRoof
	  << skip<1>
	  << b->iCurrCubesZ
	  << b->iLoop
	  << b->fAllocated
	  << b->fToDelete
	  << b->fLocated
	  << b->fReal
	  << b->fAimed
	  << skip<3>
	  << b->uiLastUpdate
	  << b->ubTilesPerUpdate
	  << skip<1>
	  << b->usClockTicksPerUpdate
	  << skip<4>
	  << b->sTargetGridNo
	  << b->sHitBy
	  << skip<2>
	  << b->iImpact
	  << b->iImpactReduction
	  << b->iRange
	  << b->iDistanceLimit
	  << b->usFlags
	  << skip<2>
	  << b->pAniTile
	  << b->pShadowAniTile
	  << b->ubItemStatus
	  << skip<3>;
}
